---
kind: pipeline
type: exec
name: dev

platform:
  os: linux
  arch: amd64

steps:
- name: dev-containers
  environment:
    MONGODB_URI:
      from_secret: MONGODB_URI
    JWT_SECRET:
      from_secret: JWT_SECRET
    DB_NAME:
      from_secret: DB_NAME
    EMAIL_CREDENTIALS:
      from_secret: EMAIL_CREDENTIALS
  commands:
  - echo $MONGODB_URI

trigger:
  branch:
  - dev
  event:
  - push