---
kind: pipeline
type: exec
name: dev

platform:
  os: linux
  arch: amd64

steps:
- name: dev-containers
  environment:
    MONGODB_URI:
      from_secret: MONGODB_URI
    JWT_SECRET:
      from_secret: JWT_SECRET
    DB_NAME:
      from_secret: DB_NAME
    EMAIL_CREDENTIALS:
      from_secret: EMAIL_CREDENTIALS
  commands:
  - echo $MONGODB_URI
  - echo $JWT_SECRET
  - echo $DB_NAME
  - echo $EMAIL_CREDENTIALS
  - docker stop apex-frontend-dev || true && docker rm apex-frontend-dev || true && docker stop apex-backend-dev || true && docker rm apex-backend-dev || true
  - cd ./apex-airline-system/frontend
  - docker build --no-cache --build-arg MONGODB_URI=$MONGODB_URI --build-arg JWT_SECRET=$JWT_SECRET --build-arg DB_NAME=$DB_NAME -t apex-frontend .
  - docker run -d --name apex-frontend-dev -p 3001:3000 apex-frontend
  - docker run -d --name apex-backend-dev -p 3002:8080 apex-backend

trigger:
  branch:
  - dev
  event:
  - push