name: Build

on:
  pull_request:
    branches:
      - main
      - uat
      - dev

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          cd apex-airline-system/backend
          ./gradlew build sonar --info
  
  notify:
    name: Notify on failure
    needs: build
    runs-on: ubuntu-latest
    if: failure()

    steps:
      - name: Execute cURL command to send mail
        run: |
          curl -X POST https://api.mailersend.com/v1/email \
          -H 'Content-Type: application/json' \
          -H 'X-Requested-With: XMLHttpRequest' \
          -H 'Authorization: ${{ secrets.API_TOKEN }}' \
          -d '{
              "from": {
                  "email": "MS_2i236R@trial-z86org8v5y1lew13.mlsender.net"
              },
              "to": [
                  {
                      "email": "jflores@unis.edu.gt"
                  }
              ],
              "subject": "SonarQube Failure",
              "text": "Unfortunately, the SonarQube scan has failed.",
              "html": "Unfortunately, the SonarQube scan has failed."
          }'